package:
  name: requests
  version: "2.9.1"

source:
  fn: requests-2.9.1.tar.gz
  url: https://pypi.python.org/packages/f9/6d/07c44fb1ebe04d069459a189e7dab9e4abfe9432adcd4477367c25332748/requests-2.9.1.tar.gz
  md5: 0b7f480d19012ec52bab78292efd976d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - requests = requests:main
    #
    # Would create an entry point called requests that calls requests.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - requests
    - requests.packages
    - requests.packages.chardet
    - requests.packages.urllib3
    - requests.packages.urllib3.contrib
    - requests.packages.urllib3.packages
    - requests.packages.urllib3.packages.ssl_match_hostname
    - requests.packages.urllib3.util

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://python-requests.org
  license: Apache Software License
  summary: 'Python HTTP for Humans.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
